# Generated by Django 4.0.4 on 2022-04-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_newsletter_title_alter_newsletter_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='created_by',
        ),
    ]
