# Generated by Django 4.0.4 on 2022-04-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_newsletter_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
