# Generated by Django 4.0.4 on 2022-04-28 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_user_roles_user_duties_user_is_ceo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('package', models.CharField(max_length=70)),
                ('price', models.CharField(max_length=20)),
                ('plans', models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Prmium')], default='basic', max_length=29)),
            ],
        ),
        migrations.RenameField(
            model_name='sessions',
            old_name='session_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='sessions',
            old_name='session_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plans',
        ),
        migrations.AddField(
            model_name='sessions',
            name='description',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default=0, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='duties',
            field=models.CharField(choices=[('Community manager', 'Community manager'), ('Accountant', 'Accountant'), ('IT Support', 'IT Support'), ('Admin', 'Admin'), ('CEO', 'CEO')], default='user', max_length=29),
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('topic', models.CharField(max_length=90)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
