# Generated by Django 4.0.4 on 2022-04-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='title',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='topic',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plans',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium')], default='basic', max_length=29),
        ),
    ]
